name: Vérification commit sur main

on:
  push:
    branches:
      - main

jobs:
  test-commit-feature:
    runs-on: windows-latest

    steps:
      - name: Afficher message de test
        run: echo "test commit_main"
