name: Détection merge direct feature → preprod

on:
  push:
    branches:
      - preprod

jobs:
  detect-merge:
    runs-on: windows-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # On récupère les 2 derniers commits pour analyse

      - name: Lire le message du dernier commit
        id: merge_check
        run: |
          echo "🔍 Lecture du message du dernier commit..."
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Message : $COMMIT_MSG"

          if echo "$COMMIT_MSG" | grep -iq "Merge branch 'feature'"; then
            echo "merge_detected=true" >> $GITHUB_OUTPUT
          else
            echo "merge_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Afficher le message si merge détecté
        if: steps.merge_check.outputs.merge_detected == 'true'
        run: echo "✅ merge de feature to preprod"


