name: SonarCloud Analysis

on:
  push:
    branches:
      - feature
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - feature

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}